# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
xcodeproj_path = "Application/Application.xcodeproj"

platform :ios do
  desc "Description of what the lane does"
  lane :test do
    apple_api_key = app_store_connect_api_key(
      key_id: "XXXXXXXX",
      issuer_id: "AAAAAAAA-dabb-47e3-e053-AAAAAAAA",
      key_filepath: "./fastlane/AuthKey_XXXXXXXX.p8",
      duration: 1200,
      in_house: false,
    )
    match(type: "development", app_identifier: "com.nah.Flute", api_key: apple_api_key)
    app_build_number = ENV["BUILD_NUMBER"]
    increment_build_number(build_number: app_build_number, xcodeproj: xcodeproj_path)
    gym(export_method: "development", scheme: "Application", output_name: "Application.ipa")
  end
end
